### ISSUE TITLE
Support PHP Plugin

### ISSUE THREAD

**Issue by aooohan** [version-fox/vfox-php#1]
https://www.php.net/downloads.php

**Comment by heheda123123** [comment]
java和php是对版本最敏感的两种环境，php确实有必要

**Comment by heheda123123** [comment]
可以参考同类产品的bin来源 https://github.com/gvcgo/version-manager

**Comment by aooohan** [comment]
<img width="854" alt="image" src="https://github.com/version-fox/vfox-php/assets/40265686/6b25fd7e-a603-4463-8e4d-7bfd7839e153">

@Chance-fyi  太帅了, 编译通过了.

**Comment by Chance-fyi** [comment]
我在写 Test workflow
shell 挂载不了

![image](https://github.com/version-fox/vfox-php/assets/37658940/3dc4fb8e-7072-4355-8af3-b0e74d65ac72)

直接执行 `eval "$(vfox env -s bash)"` 生成的 PATH 莫名多了个 $ 

![image](https://github.com/version-fox/vfox-php/assets/37658940/ac58d89e-ad20-427b-b717-87bed6e59cde)

搞了一下午没解决，帮忙看看能解决不，不行就放弃测试 use 了

**Comment by aooohan** [comment]
> 搞了一下午没解决，帮忙看看能解决不，不行就放弃测试 use 了

ok

**Comment by aooohan** [comment]
@Chance-fyi 应该好了,  安装vfox耽误太多时间,哈哈. scoop和brew分别有各自的问题, 哎.

**Comment by Chance-fyi** [comment]
只有 windows 的在执行，unix 那个文件语法错误了

**Comment by aooohan** [comment]
> 只有 windows 的在执行，unix 那个文件语法错误了

加了个注释导致的, aciton的brew真的要搞死人了, 明明homebrew core仓库已经更新了. 还不能直接用brew install vfox. 😂
